### ISSUE TITLE
Please update for MW 1.26 compatibility.

### ISSUE THREAD

**Issue by Alexia** [Telshin/Spoilers#10]
This should include the new extension.json file and the ability to use wfLoadExtension().  See maintenance/convertToExtensionRegistration.php.

**Comment by Telshin** [comment]
Thanks for the report. I'll get started on this soon.

**Comment by Alexia** [comment]
Would you have any issues with me having @applehat work on this and put in a pull request?

**Comment by Telshin** [comment]
I have no issue with that at all.

**Comment by applehat** [comment]
Pull Request Inbound: https://github.com/Telshin/Spoilers/pull/12

**Comment by applehat** [comment]
@Telshin this can be closed =)

**Comment by Telshin** [comment]
Yep. I forgot to close it after the merge. Thanks again for the PR!
