### ISSUE TITLE
Messed markup

### ISSUE THREAD

**Issue by DavidSarif** [Telshin/Spoilers#19]
If spoiler is used with indentation (for example `:<spoiler>blabla</spoiler>`) page markup is messed up and sidebar is not usable.

It looks like [this](https://mrakopedia.ru/w/images/8/8d/Brokenpageproof.png).

**Comment by Telshin** [comment]
Thanks for the report. One of us will check it out.

**Comment by ghost** [comment]
Hi @DavidSarif,

Could I have a link to a live MediaWiki instance of where this is causing an issue. (I've not currently got a Wiki with this extension installed to see the effects of this)

**Comment by DavidSarif** [comment]
Example is here:
https://mrakopedia.ru/wiki/Участник:Toriningen/СломанныйСпойлер

First spoiler is working: the second is glitched.

**Comment by ghost** [comment]
Thank you for that, will hopefully have a fix for it with V2 of this release :+1:

**Comment by ghost** [comment]
Resolved as of V2.0 [76aa237]
