### ISSUE TITLE
Messed up button text

### ISSUE THREAD

**Issue by fireton** [Telshin/Spoilers#23]
When button appears on the load of the page it has no text. When I pressed it - spoler text is shown and "show" text appears on the button. Tried to switch off every extension I have but no luck, I couldn't find any conflict.

See for yourself it here: http://ifwiki.ru/%D0%96%D1%83%D1%87%D0%BA%D0%BE%D0%B2,_%D0%90%D0%BD%D1%82%D0%BE%D0%BD

**Comment by ghost** [comment]
This is currently being investigated by myself, thank you for the report :) We will update accordingly when we have a fix.

**Comment by sattellite** [comment]
This PR #24 fixes this problem

**Comment by ghost** [comment]
Thanks, will check and review this when I get back home :)

**Comment by ghost** [comment]
Fixed as of b299b77c71018398f93618908ed8dbcd769f81c8
