### ISSUE TITLE
Change to MIT license

### ISSUE THREAD

**Issue by ghost** [Telshin/Spoilers#26]
- [x] @applehat 
- [x] @Developaws
- [x] @must-not-code 
- [x] @Telshin

**Comment by Telshin** [comment]
I vote yes to this license change.

**Comment by applehat** [comment]
Works for me.

**Comment by Telshin** [comment]
Are you good with the change @must-not-code ?

**Comment by must-not-code** [comment]
yep

**Comment by Telshin** [comment]
Voting has been completed and pass. We will switch to a MIT license.
