### ISSUE TITLE
Spoiler Extension on MW 1.30

### ISSUE THREAD

**Issue by Jcognard** [Telshin/Spoilers#29]
I've installed this extension on MW 1.30 and, when used on a page, one message line "_Array ( [show] => see details [hide] => hide details [text] => 'UNIQ--DPL-00000001-QINU' )_" is displayed on upper side.

Could it be fixed ?

**Comment by Telshin** [comment]
I won’t be able to get to it for the first half this week. Will try and get this resolved soon. Thanks for letting us know!
