### ISSUE TITLE
Spoiler 'show' attribute does not work

### ISSUE THREAD

**Issue by KarelWintersky** [Telshin/Spoilers#31]
Example: 

[Usage example](https://jtts.wiki.wintersky.me/wiki/%D0%93%D0%B2%D0%B0%D1%80%D0%B4%D0%B5%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%BE%D0%BB%D0%BA)

This spoiler created as:
```
<spoiler show="цитата (показать)" hide="цитата (скрыть)">
A lot of text
</spoiler>
```

but works as `Показать спойлер` / `цитата (скрыть)`

**Comment by ovvldc** [comment]
There was a bug in SpoilersHooks.php. I submitted a pull request. Hope that helps.

**Comment by Telshin** [comment]
Fixed! Will add it to the next release.
