### ISSUE TITLE
Every line of text inside <spoiler></spoiler>text gets automatically surrounded by <p> </p> tags

### ISSUE THREAD

**Issue by ovvldc** [Telshin/Spoilers#33]
This means you cannot make spoilers that start with lists or intended lines:
*
#
:

Was the extension never meant to be used for more than one line?

**Comment by ovvldc** [comment]
Actually, the bug seems to be that the <spoiler> tag assumes to end at the end of the line in wiki-format, if you are in a list. So

```
<spoiler>text

*more text</spoiler>

```
will work, but

```
*text <spoiler>

:more text</spoiler>
```

does not.

Reply

**Comment by ghost** [comment]
Ahoy,

As our readme usage specifies, you should be using new lines. This is how MediaWiki supports tags.
```
<spoiler>
* text
: more text
</spoiler>
```

**Comment by ovvldc** [comment]
I do, now. I just wanted to know if there was a way around it.
