### ISSUE TITLE
addModules with non-array argument was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by seapancake** [Telshin/Spoilers#37]
Just realized we are seeing these errors on our Mediawiki Virtual Server.

[Tue Oct 18 08:31:29.153596 2022] [proxy_fcgi:error] [pid 2115157:tid 140118157399808] [client 162.158.62.216:56338] AH01071: Got error 'PHP message: PHP Deprecated:  Use of ParserOutput::addModules with non-array argument was deprecated in MediaWiki 1.38. [Called from Spoilers\\SpoilersHooks::spoilerMagicTag in /home/wiki/public_html/extensions/Spoilers/SpoilersHooks.php at line 62] in /home/wiki/public_html/includes/debug/MWDebug.php on line 377'
[Tue Oct 18 08:31:56.194557 2022] [proxy_fcgi:error] [pid 2115079:tid 140118476191488] [client 162.158.62.18:23382] AH01071: Got error 'PHP message: PHP Deprecated:  Use of ParserOutput::addModules with non-array argument was deprecated in MediaWiki 1.38. [Called from Spoilers\\SpoilersHooks::spoilerMagicTag in /home/wiki/public_html/extensions/Spoilers/SpoilersHooks.php at line 62] in /home/wiki/public_html/includes/debug/MWDebug.php on line 377'

We are running the below versions with version 2.2.0 of the extension.

MediaWiki 	1.38.2
MariaDB 	10.3.34-MariaDB-0ubuntu0.20.04.1

I have tested and the extension works as expected however it does log the log error.

**Comment by Telshin** [comment]
This has been fixed. Will cut a new version later today.
